version: '3'

services:
  db_postgres:
    image: 'docker.io/postgres:15.2-alpine'
    volumes:
      - '../volumes/bbook/db_postgres:/var/lib/postgresql/data'
    env_file:
      - '.env.development'
    ports:
      - '5432:5432'
