# typed: true
# frozen_string_literal: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Api::V1::ApplicationController`.
# Please instead update this file by running `bin/tapioca dsl Api::V1::ApplicationController`.

module Api
  module V1
    class ApplicationController
      include GeneratedUrlHelpersModule
      include GeneratedPathHelpersModule
    end
  end
end
